python: can't open file '/Users/nidhipatel/Desktop/Ecommerce_Analysis/stock_data_pipeline/store_sp500_to_mongodb.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/stock_data_pipeline/store_sp500.py", line 3, in <module>
    from get_sp500_symbols import get_sp500_tickers
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/stock_data_pipeline/get_sp500_symbols.py", line 1, in <module>
    import requests
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/myenv/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/myenv/lib/python3.12/site-packages/urllib3/__init__.py", line 15, in <module>
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/myenv/lib/python3.12/site-packages/urllib3/_base_connection.py", line 5, in <module>
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/myenv/lib/python3.12/site-packages/urllib3/util/__init__.py", line 8, in <module>
  File "/Users/nidhipatel/Desktop/Ecommerce_Analysis/myenv/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 133, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nidhipatel/Desktop/Ecommerce_Analysis/myenv/lib/python3.12/site-packages/urllib3/util/ssltransport.py'
